[package]
name = "defistory"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4.0.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
env_logger = "0.9.0"
futures = "0.3.18"
serde = "1.0.0"
serde_json = "1.0"
serde_derive = "1.0"
dotenv = "0.15.0"
chrono = {version = "0.4", features = ["serde"]}
actix-service = "2.0.2"
alcoholic_jwt = "4091.0.0"
reqwest = "0.11.11"
actix-rt = "2.7.0"
