[package]
name = "messages-actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
serde = "1.0.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = {version = "1.4.8", features = ["postgres"]}
dotenv = "0.15.0"
futures = "0.3.18"
juniper = "0.15.9"
env_logger = "0.9.0"

[dependencies.mongodb]
tokio = {version = "1.18.2", features = ["full"]}
futures = "0.3.21"
version = "2.2.1"
default-features = false
# features = ["async-std-runtime"]
