[package]
name = "messages-actix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0.0"
env_logger = "0.9"
serde = "1.0.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = {version = "1.4.0", features = ["postgres", "r2d2"]}
dotenv = "0.15.0"
futures = "0.1"
