[package]
name = "defistory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "defistory"

[dependencies]
actix-web = "3.3.3"
actix-cors= "0.5.4"
actix-web-httpauth = "0.6.0"
env_logger = "0.9.0"
futures = "0.3.18"
serde = "1.0.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = {version = "1.4.8", features = ["postgres", "r2d2", "chrono", "uuidv07"]}
dotenv = "0.15.0"
chrono = {version = "0.4", features = ["serde"]}
actix-service = "2.0.2"
alcoholic_jwt = "4091.0.0"
reqwest = "0.11.11"
actix-rt = "2.7.0"